# Site
name: "Jaya Mishra"
title: "Jaya Mishra"
description: "Jaya Mishra"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Jaya:
    name: JM
    display_name: Jaya Mishra
    gravatar: 982ca7ed42068da301c6b04507980ca2
    email: mail@jayamishra.com
    web: https://jayamishra.com
    twitter: https://twitter.com/jayamishrapoet
    description: "Author of Her Green Diary and Intentions (Coming Soon) -  Jaya Mishra is a poet, writer and physician."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
#highlighter: 
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
